### ISSUE TITLE
Is this plugin needed?

### ISSUE THREAD

**Issue by spdustin** [bramley/phplist-plugin-amazonses#1]
Is this plugin needed when using latest version of PHPList? How does it differ from the built-in Amazon SES API sending integration?

**Comment by bramley** [comment]
The plugin can increase the sending rate if you enable the "send emails concurrently" setting. If the sending rate is not an issue then you can use the core phplist function.
The plugin documentation is at https://resources.phplist.com/plugin/amazonses
