### ISSUE TITLE
Uncaught Error: Class 'phpList\plugin\AmazonSes\MailClient' while trying to send a campaign

### ISSUE THREAD

**Issue by komodin** [bramley/phplist-plugin-amazonses#2]
Hi,
I'm using phpList 3.4.2 with the current version of this plugin, and when I try to send the test email I get this error:

> 2019/06/12 15:57:50 [error] 25509#25509: *22740 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'phpList\plugin\AmazonSes\MailClient' not found in /srv/phplist/lists/admin/plugins/AmazonSes.php:143
> Stack trace:
> #0 /srv/phplist/lists/admin/class.phplistmailer.php(826): AmazonSes->send(Object(PHPlistMailer), 'Received: from ...', 'This is a multi...')
> #1 /srv/phplist/lists/admin/PHPMailer/class.phpmailer.php(1463): PHPlistMailer->pluginSend('Received: from ...', 'This is a multi...')
> #2 /srv/phplist/lists/admin/PHPMailer/class.phpmailer.php(1327): PHPMailer->postSend()
> #3 /srv/phplist/lists/admin/class.phplistmailer.php(315): PHPMailer->send()
> #4 /srv/phplist/lists/admin/sendemaillib.php(949): PHPlistMailer->compatSend('', 'email1@gmail....', 'support@hidde...', 'support@hidde...', 'Mail de prueba')
> #5 /srv/phplist/lists/admin/send_core.php(493): sendEmail('3', 'email1@gmail....', '309aa6bfed7a484...', '1')
> #6 /srv/phplist/lists/admin/send.php(120): include('/srv/phplist/li...')
> #7 /srv/phplist/lists/admin/index.php(751): include('/srv/phpli" while reading response header from upstream, client: 172.31.100.106, server: phplist.hidden.domain, request: "POST /lists/admin/?page=send&id=3&tk=0a9b7ecf178f5bfd08175f22ac6944a3 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "phplist.hidden.domain", referrer: "https://phplist.hidden.domain/lists/admin/?page=send&id=3&tk=0a9b7ecf178f5bfd08175f22ac6944a3"

I can't figure out if it's a misconfiguration on my installation or if something changed on the latest version of phpList.

Thanks in advance!

**Comment by bramley** [comment]
It looks like you have not installed the plugin correctly. There should be a file AmazonSes.php and a directory AmazonSes.

**Comment by komodin** [comment]
I have both of them with the correct owner/group and permissions:

![image](https://user-images.githubusercontent.com/383352/59381597-2f1fb880-8d32-11e9-8d1b-4c0f2cf1bcdd.png)

**Comment by bramley** [comment]
There should be a file MailClient.php in the AmazonSes directory.

**Comment by komodin** [comment]
There it is, and they has the same md5sum as the files in the master branch of this repo:

![image](https://user-images.githubusercontent.com/383352/59382054-2ed3ed00-8d33-11e9-95fd-8e07ac7e9c80.png)

**Comment by bramley** [comment]
Sorry but I don't know. It works for me with phplist 3.4.3 RC2, and php 7.2.19. Do any other plugins work, such as Subscribers plugin or Message Statistics plugin?

**Comment by komodin** [comment]
Finally we figured out that we had the `CommonPlugin` plugin disabled. Sorry for wasting your time and thanks for the help!
