### ISSUE TITLE
Sender SignatureDoesNotMatch Credential

### ISSUE THREAD

**Issue by sjAbaquita** [bramley/phplist-plugin-amazonses#4]
I always got this error when sending an email. I already generated a new credentials but got same error. 

> Multi-curl http code 403 result HTTP/1.1 100 Continue HTTP/1.1 403 Forbidden Date: Wed, 07 Apr 2021 16:56:46 GMT Content-Type: text/xml Content-Length: 327 Connection: keep-alive x-amzn-RequestId: 62845bb2-a01f-4a31-85bf-6c9bb8Sample Sender SignatureDoesNotMatch Credential should be scoped to a valid region, not 'AWS Access ID'.

**Comment by bramley** [comment]
It looks like you might not have entered the correct details on the Settings page.

**Comment by sjAbaquita** [comment]
It was already up and running before we update the plugin due to deprecated authentication. That was the error after we updated the plugin.

**Comment by sjAbaquita** [comment]
And also the field for region is not present on the settings.

**Comment by bramley** [comment]
If the region field is not on the Settings page then you cannot be using the current version of the plugin. Upgrade on the Manage Plugins page.

**Comment by sjAbaquita** [comment]
Already upgraded the plugin on Manage Plugins and says 

> AmazonSes updating existing plugin

> AmazonSes.php updating existing plugin

> Plugin installed successfully 

and still region field is not showing.

**Comment by bramley** [comment]
Please show me the details of the plugin  on the Manage Plugins page
![image](https://user-images.githubusercontent.com/3147688/113984991-94b43180-9843-11eb-9446-14cb87efa688.png)

![image](https://user-images.githubusercontent.com/3147688/113985242-da70fa00-9843-11eb-9cc6-c0ad81ef159e.png)

**Comment by sjAbaquita** [comment]
![image](https://user-images.githubusercontent.com/44889878/113985533-d6160280-987e-11eb-86c1-37a3bac7e7ca.png)
![image](https://user-images.githubusercontent.com/44889878/113985687-02318380-987f-11eb-9564-3477982c3146.png)

**Comment by bramley** [comment]
Did you ever install the plugin manually, not through phplist? I am guessing that one of the files is not being overwritten by the update through phplist.
Check the file permissions by using a file manager or ftp to look at the phplist files
directory lists/admin/plugins
do the file permissions for file AmazonSes.php look correct?

Try deleting the plugin using the trash icon then installing again.
Otherwise manually remove AmazonSes.php and the directory AmazonSes, then install the plugin again.

**Comment by sjAbaquita** [comment]
After the update I encounter this new error
![Capture](https://user-images.githubusercontent.com/44889878/113996877-2ba3dc80-988a-11eb-8009-45aeacbc3fae.PNG)

**Comment by bramley** [comment]
I'm not sure. When I encountered this error I resolved it by creating a new access key on the Amazon Identity and Access Management (IAM) page
But check that your SES account has not been restricted in some way first.

Also, you are now using region us-west-2 but your screenshot showed us-east-1. Note that access keys are specific to each region.

**Comment by sjAbaquita** [comment]
I already created a new one with Ses full access but encountered same error. I am configuring a new one hope no error will come up. Thanks bramley

**Comment by bramley** [comment]
You don't need a new user, just new access key

![image](https://user-images.githubusercontent.com/3147688/114012777-ac4ce380-985e-11eb-93e0-b6bdcd0eea83.png)

**Comment by sjAbaquita** [comment]
Thanks for your response, it creates ideas on how to resolve the issue. The problem is the files is not overwritten by the update on phplist. What I did is deleting the AmazonSes plugin and reinstall it, but still encounter the error. what I forgot to update is the Common Plugin and change the region. No idea which one resolve the issue but it fixes the problem.
