### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by xcellenceit** [bramley/phplist-plugin-amazonses#5]
I am using PHPList version v3.6.6 and trying out AWS SES to send emails using an add-on/plugin https://resources.phplist.com/plugin/amazonses and configured everything including Access Key as described.

While trying to send email I get following error being logged in PHPLIST:

MailSender http code: 0, result: , curl error: Failed to connect to email-smtp.us-east-2.amazonaws.com port 443: Connection timed out

Any idea, how to make it work? What could be wrong?

**Comment by bramley** [comment]
You have entered an incorrect endpoint. The plugin uses the SES API not the SMTP interface. You probably meant `https://email.us-east-2.amazonaws.com`

**Comment by xcellenceit** [comment]
Thank you, this helped.
